<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'mineichen\\entitymanagerbundle\\dependencyinjection\\compiler\\repositorycompilerpass' => '/DependencyInjection/Compiler/RepositoryCompilerPass.php',
                'mineichen\\entitymanagerbundle\\dependencyinjection\\mineichenentitymanagerextension' => '/DependencyInjection/mineichenEntityManagerExtension.php',
                'mineichen\\entitymanagerbundle\\mineichenentitymanagerbundle' => '/mineichenEntityManagerBundle.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd